### ISSUE TITLE
Missing Thai translation for Sirens and Disasters

### ISSUE THREAD

**Issue by Konijima** [Konijima/PZ-Random-Sound-Events#3]
Missing Thai translation for the Sirens and Disasters mods.

## Thai Translations
- [x] RandomSoundEvents
- [x] RandomSoundEvents_Nukes
- [ ] RandomSoundEvents_Disasters
- [ ] RandomSoundEvents_Sirens

@radiusgreenhill

**Comment by rikoprushka** [comment]
I’ll work on it right now.

**Comment by rikoprushka** [comment]
@Konijima All tasks are completed.
